"""
Django settings for Choroba project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))


MEDIA_ROOT = BASE_DIR + '/media/'

TEMPLATE_DIRS = (
    BASE_DIR + '/templates/',
)
SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^tm++kq+^#4h9hftwh9j*d^*c4^!m0b9tqig4r6s90k3h41vn*'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',
    'djangular',
    'mongoengine.django.mongo_auth',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Choroba.urls'

WSGI_APPLICATION = 'Choroba.wsgi.application'
# = 'mongo_auth.MongoUser'

# # MongoDB settings
# MONGODB_DATABASES = {
#     'default': {'name': 'django_mongoengine'}
# }
#DJANGO_MONGOENGINE_OVERRIDE_ADMIN = True
DATABASES = {
    'default': {
        'ENGINE':'',
        'NAME': 'misiowa',
    },
}
SESSION_ENGINE = 'mongoengine.django.sessions' # optional
AUTH_USER_MODEL = 'mongo_auth.MongoUser'
MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User'

# DATABASES = {
#     'default': {'ENGINE': 'django.db.backends.dummy'}
# }
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django_mongodb_engine',
#         'NAME': 'misiowa'
#     }
# }
# import mongoengine

# DATABASES = {
#     'default': {
#         'ENGINE': '',
#       'NAME': ''
#     },
# }
#
# SESSION_ENGINE = 'mongoengine.django.sessions' # optional
# _MONGODB_USER = 'lala'
# _MONGODB_PASSWD = '123456'
# _MONGODB_HOST = '127.0.0.1'
# _MONGODB_NAME = 'misiowa'
# _MONGODB_DATABASE_HOST = \
#     'mongodb://%s:%s@%s/%s' \
#     % (_MONGODB_USER, _MONGODB_PASSWD, _MONGODB_HOST, _MONGODB_NAME)
#
# #mongoengine.connect(_MONGODB_NAME, host=_MONGODB_DATABASE_HOST)
# mongoengine.connect('misiowa')
# AUTHENTICATION_BACKENDS = (
#     'mongoengine.django.auth.MongoEngineBackend',
# )
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL="/static/"
STATICFILES_DIRS = ( os.path.join(BASE_DIR, "static"), )
DEBUG=True
TEMPLATE_DEBUG=True